steps:
  - name: node:16.14.2
    entrypoint: npm
    args: ['install']
  - name: node:16.14.2
    entrypoint: npm
    args: ['--openssl-legacy-provider', 'run', 'generate']
  - name: gcr.io/yfthig-dev/firebase
    args: ['hosting:channel:deploy', '--project=yfthig-dev', 'PR-$_PR_NUMBER']
