steps:
  # install / setup ci
  - name: node:16.14.2
    entrypoint: npm
    args: ['install']
  #
  # Generate the statis site
  #
  - name: node:16.14.2
    entrypoint: npm
    args: ['--openssl-legacy-provider', 'run', 'generate']
  #
  # Deploy to firebase channel, using the PR #
  # store log to /workspace to get the channel URL
  #
  - name: gcr.io/yfthig-dev/firebase
    entrypoint: bash
    args: ['-c', 'firebase hosting:channel:deploy --project=yfthig-dev PR-$_PR_NUMBER > /workspace/firebase-deploy.txt']
  #
  # Update the PR with the temporary URL
  #
  - id: "Update the PR"
    name: gcr.io/cloud-builders/curl
    entrypoint: bash
    args:
      - -c
      - |
        generate_post_data()
        {
        cat <<EOF
        {"body": "$message"}
        EOF
        }
        # Read from "/workspace"
        url=`cat /workspace/firebase-deploy.txt| grep 'Channel URL'| cut -c 77-`
        message=`echo "Temporary Url for review: $url"`
        echo "this is the body:" $(generate_post_data)
        echo "posted to: https://api.github.com/repos/bcgov/bcregistry/issues/$_PR_NUMBER/comments"
        curl -X POST \
        -H "Authorization: Token $$TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/bcgov/bcregistry/issues/$_PR_NUMBER/comments \
        -d '$(generate_post_data)'

    secretEnv: ['TOKEN']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/github-appkey/versions/latest
    env: 'TOKEN'

