steps:
  - name: node:16.14.2
    entrypoint: npm
    args: ['install']
  - name: node:16.14.2
    entrypoint: npm
    args: ['--openssl-legacy-provider', 'run', 'generate']
  - name: gcr.io/yfthig-dev/firebase
    entrypoint: bash
    args: ['-c', 'firebase hosting:channel:deploy --project=yfthig-dev PR-$_PR_NUMBER > firebase-deploy.txt']
